version: '3'

services:
 adventuregamesapi:
  container_name: adventuregamesapi
  build: 
   context: .
   dockerfile: OpenApi\Dockerfile
  ports:
   - "5000:80"
  links:
   - redis
   
 redis:
  image: redis
  container_name: rediscache
  volumes:
   - .\redis.conf:/tmp/redis.conf
  ports:
   - "6379:6379"
  command: [ "redis-server", "/tmp/redis.conf"]