version: '3'

services:
 openapi:
  image: openapi
  ports:
   - "5000:80"
  links:
   - redis
   
 redis:
  image: redis
  volumes:
   - .\redis.conf:/tmp/redis.conf
  ports:
   - "6379:6379"
  command: [ "redis-server", "/tmp/redis.conf"]
